name: Windows

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
    steps:
    - uses: actions/checkout@v3.5.2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
    - name: Build
      shell: cmd
      run: msbuild R3nzSkin/R3nzSkin.vcxproj -p:Platform=x64 -p:Configuration=RiotGamesServers -p:Instruction_Set=AdvancedVectorExtensions2
    - run: msbuild R3nzSkin_Injector/R3nzSkin_Injector.vcxproj -p:Platform=x64 -p:Configuration=RiotGamesServers -p:Instruction_Set=AdvancedVectorExtensions2
    - name : Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: R3nzSkin.dll
        path: R3nzSkin/Release/RiotGamesServers/
    - name : Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: R3nzSkin_Injector.exe
        path: R3nzSkin_Injector/Release/RiotGamesServers/
