name: Windows

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        configuration: [RiotGamesServers]
    steps:
    - uses: actions/checkout@v3.5.2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
    - name: Build
      shell: cmd
      run: msbuild R3nzSkin/R3nzSkin.vcxproj /p:Platform=x64 /p:Configuration=${{ matrix.configuration }} /p:CL_AdditionalOptions="/arch:AVX2"
    - name: Show files
      shell: cmd
      run: dir /s
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: R3nzSkin-AVX2
        path: R3nzSkin\R3nzSkin\R3nzSkin-AVX2\Release\**
